apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: tungtt1006/test:1.2.0
    ports:
    - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-s6m
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - test.s6m.io
      secretName: test.s6m.io
  rules:
    - host: test.s6m.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: test
                port:
                  number: 3000
